### ISSUE TITLE
new orrms.server.utils.moment(newVal).getDateTime();

### ISSUE THREAD

**Issue by ghedwards** [psarin/cfml-firebase#1]
Is this an external lib ?

new orrms.server.utils.moment(newVal).getDateTime();

**Comment by psarin** [comment]
Good catch. Yes, it refers to [Moment.cfc](https://github.com/AlumnIQ/momentcfc). I have updated the code and pushed new version. Let me know if any issues.

**Comment by psarin** [comment]
@ghedwards Closing the issue since I haven't back from you. Feel free to open up again if neeed. Thanks.
